Repository ARMmbed/mbl-manifest, pull requests merged in 2019-11, with the labels that each got.

#133 Change to HTTPS for repo pull
  default.xml
Labels: SYNCHRONIZE MERGES

#134 master: sync up with warrior-dev
  default.xml
Labels: SYNCHRONIZE MERGES, sync: dev->master

#136 zeus-dev: sync up with warrior-dev
  poky.xml
Labels: DO NOT MERGE, SYNCHRONIZE MERGES, sync: warrior-dev->zeus-dev
